---

- name: Add MariaDB 10.2 repository key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present

- name: Add MariaDB 10.2 repository
  apt_repository:
    repo: 'deb [arch=amd64] http://mirror.zol.co.zw/mariadb/repo/10.2/ubuntu bionic main'
    state: present
    filename: mariadb.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: latest

- name: Start and enable MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Set Magento Database User
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "*.*:ALL"
    state: present

- name: Set Magento Database
  mysql_db:
    name: "{{ db_name }}"
    state: present
