- name: Update package manager
  become: true
  apt:
    update_cache: yes

- name: Install Java 8
  become: true
  apt:
    name: openjdk-8-jdk
    state: present

- name: Import Elasticsearch GPG key
  become: true
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add Elasticsearch repository
  become: true
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    filename: elastic-7.x

- name: Install Elasticsearch
  become: true
  apt:
    name: elasticsearch
    state: present

- name: Enable Elasticsearch on boot
  become: true
  systemd:
    name: elasticsearch
    enabled: yes

- name: Start Elasticsearch
  become: true
  systemd:
    name: elasticsearch
    state: started


